export const PLANET_CATEGORIES = [
  'INNER SOLAR SYSTEM',
  'GIANT PLANETS',
  'DWARF / SMALL BODIES',
  'MAJOR MOONS',
  'EXOPLANET ARCHIVE',
]

export const PLANETS = [
  {
    id: 'mercury',
    name: 'Mercury',
    subtitle: 'The Swift World',
    category: 'INNER SOLAR SYSTEM',
    type: 'Terrestrial Planet',
    diameter: '4,879 km',
    distanceFromSun: '57.9 million km',
    temperature: '-173°C to 427°C',
    atmosphere: 'Extremely thin exosphere',
    gravity: '0.38 g',
    color: '#9ca3af',
    textureUrl: '/textures/mercury.png',
    surfaceTag: 'Cratered iron world',
    moonCount: 0,
    magneticField: 'Weak global field',
    explorationDifficulty: 'High',
    discoveryStatus: 'Ancient observation',
    orbitalPeriod: '88 Earth days',
    rotationPeriod: '58.6 Earth days',
    moons: [],
    missionHighlights: ['Mariner 10 flybys', 'MESSENGER orbiter', 'BepiColombo en route'],
    visualPalette: ['#4b5563', '#9ca3af', '#d1d5db', '#f8fafc'],
    namingOrigin: 'Mercury was named after the swift Roman messenger god.',
    archiveNote: 'Mercury is a compact record of impacts, solar heat, and the difficulty of orbiting close to the Sun.',
    observationRecord: {
      firstKnown: 'Ancient times',
      telescopicObservation: '17th century',
      spaceMissions: 'Mariner, MESSENGER, BepiColombo',
    },
    callouts: [
      { label: 'Caloris Basin', description: 'A vast impact basin on the sunward world', position: 'top-left' },
      { label: 'Long day', description: 'One rotation lasts almost 59 Earth days', position: 'right' },
      { label: 'Solar exposure', description: 'Surface temperatures swing dramatically', position: 'bottom-right' },
    ],
  },
  {
    id: 'venus',
    name: 'Venus',
    subtitle: 'The Veiled Planet',
    category: 'INNER SOLAR SYSTEM',
    type: 'Terrestrial Planet',
    diameter: '12,104 km',
    distanceFromSun: '108.2 million km',
    temperature: '464°C average',
    atmosphere: 'Dense CO₂ with sulfuric acid clouds',
    gravity: '0.90 g',
    color: '#d8b46a',
    textureUrl: '/textures/venus.png',
    surfaceTag: 'Cloud-covered world',
    moonCount: 0,
    magneticField: 'No intrinsic field',
    explorationDifficulty: 'Extreme',
    discoveryStatus: 'Ancient observation',
    orbitalPeriod: '225 Earth days',
    rotationPeriod: '243 Earth days retrograde',
    moons: [],
    missionHighlights: ['Venera landers', 'Magellan radar mapping', 'Akatsuki orbiter'],
    visualPalette: ['#78350f', '#d8b46a', '#fde68a', '#fff7ed'],
    namingOrigin: 'Venus was named after the Roman goddess of love and beauty.',
    archiveNote: 'Venus shows how a world near Earth in size can become a furnace beneath reflective clouds.',
    observationRecord: {
      firstKnown: 'Ancient times',
      telescopicObservation: 'Galileo observed phases in 1610',
      spaceMissions: 'Venera, Magellan, Akatsuki',
    },
    callouts: [
      { label: 'Dense clouds', description: 'Reflective sulfuric acid cloud deck', position: 'top-right' },
      { label: 'Runaway greenhouse', description: 'A powerful atmospheric heat trap', position: 'right' },
      { label: 'Radar surface', description: 'Mapped through clouds by spacecraft radar', position: 'bottom-left' },
    ],
  },
  {
    id: 'earth',
    name: 'Earth',
    subtitle: 'The Blue Planet',
    category: 'INNER SOLAR SYSTEM',
    type: 'Terrestrial Planet',
    diameter: '12,742 km',
    distanceFromSun: '149.6 million km',
    temperature: '15°C average',
    atmosphere: 'Nitrogen and oxygen-rich atmosphere',
    gravity: '1.00 g',
    color: '#3b82f6',
    textureUrl: '/textures/earth.png',
    surfaceTag: 'Ocean-bearing world',
    moonCount: 1,
    magneticField: 'Strong global field',
    explorationDifficulty: 'Home reference',
    discoveryStatus: 'Human origin',
    orbitalPeriod: '365.25 Earth days',
    rotationPeriod: '23.9 hours',
    moons: [
      { name: 'Moon', orbitRadius: 2.45, size: 0.16, color: '#d1d5db', period: '27.3 days' },
    ],
    missionHighlights: ['Continuously observed from orbit', 'Apollo lunar program', 'Global climate monitoring'],
    visualPalette: ['#0f172a', '#1d4ed8', '#3b82f6', '#86efac'],
    namingOrigin: 'The name Earth comes from Old English and Germanic words meaning ground or soil.',
    archiveNote: "Earth is the observer's home. Every act of cosmic classification begins from a human point of view.",
    observationRecord: {
      firstKnown: 'Human origin',
      telescopicObservation: 'Not applicable',
      spaceMissions: 'Continuously observed from orbit',
    },
    callouts: [
      { label: 'Atmosphere', description: 'A protective nitrogen-oxygen envelope', position: 'top-left' },
      { label: 'Oceans', description: 'Liquid water covers most of the surface', position: 'right' },
      { label: 'Human origin', description: 'The archive begins from this world', position: 'bottom-right' },
    ],
  },
  {
    id: 'moon',
    name: 'Moon',
    subtitle: "Earth's Companion",
    category: 'INNER SOLAR SYSTEM',
    type: 'Natural Satellite',
    diameter: '3,475 km',
    distanceFromSun: 'Orbits Earth',
    temperature: '-173°C to 127°C',
    atmosphere: 'Trace exosphere',
    gravity: '0.17 g',
    color: '#cbd5e1',
    textureUrl: '/textures/moon.png',
    surfaceTag: 'Ancient impact terrain',
    moonCount: 0,
    magneticField: 'Localized crustal fields',
    explorationDifficulty: 'Medium',
    discoveryStatus: 'Ancient observation',
    orbitalPeriod: '27.3 Earth days',
    rotationPeriod: '27.3 Earth days',
    moons: [],
    missionHighlights: ['Apollo landings', 'Lunar Reconnaissance Orbiter', 'Artemis program'],
    visualPalette: ['#334155', '#94a3b8', '#cbd5e1', '#f8fafc'],
    namingOrigin: 'Moon comes from Old English and Germanic terms for the monthly celestial body.',
    archiveNote: 'The Moon preserves a nearby record of impacts, tides, calendars, and human exploration.',
    observationRecord: {
      firstKnown: 'Ancient times',
      telescopicObservation: 'Galileo mapped lunar terrain in 1609',
      spaceMissions: 'Luna, Apollo, Chang’e, Artemis',
    },
    callouts: [
      { label: 'Mare plains', description: 'Dark basaltic plains from ancient volcanism', position: 'left' },
      { label: 'Synchronous rotation', description: 'One face remains turned toward Earth', position: 'right' },
      { label: 'South pole', description: 'A target region for ice and exploration', position: 'bottom-right' },
    ],
  },
  {
    id: 'mars',
    name: 'Mars',
    subtitle: 'The Red Planet',
    category: 'INNER SOLAR SYSTEM',
    type: 'Terrestrial Planet',
    diameter: '6,779 km',
    distanceFromSun: '227.9 million km',
    temperature: '-63°C average',
    atmosphere: 'Thin CO₂ atmosphere',
    gravity: '0.38 g',
    color: '#c65a32',
    textureUrl: '/textures/mars.png',
    surfaceTag: 'Iron-rich desert',
    moonCount: 2,
    magneticField: 'Weak remnant field',
    explorationDifficulty: 'Medium',
    discoveryStatus: 'Ancient observation',
    orbitalPeriod: '687 Earth days',
    rotationPeriod: '24.6 hours',
    moons: [
      { name: 'Phobos', orbitRadius: 2.2, size: 0.06, color: '#b8a99a', period: '7.6 hours' },
      { name: 'Deimos', orbitRadius: 3.0, size: 0.04, color: '#9f9288', period: '30.3 hours' },
    ],
    missionHighlights: ['Viking landers', 'Curiosity rover', 'Perseverance rover'],
    visualPalette: ['#7c2d12', '#c65a32', '#f97316', '#fed7aa'],
    namingOrigin: 'Mars was named after the Roman god of war.',
    archiveNote: 'Its red surface made Mars a symbol of war, conflict, exploration, and the human imagination of other worlds.',
    observationRecord: {
      firstKnown: 'Ancient times',
      telescopicObservation: '17th century',
      spaceMissions: '60+ missions',
    },
    callouts: [
      { label: 'Polar ice caps', description: 'Seasonal carbon dioxide and water ice deposits', position: 'top-left' },
      { label: 'Valles Marineris', description: 'One of the largest canyon systems in the Solar System', position: 'right' },
      { label: 'Dust storms', description: 'Planet-wide storms can reshape the atmosphere', position: 'bottom-right' },
    ],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    subtitle: 'The Giant Planet',
    category: 'GIANT PLANETS',
    type: 'Gas Giant',
    diameter: '139,820 km',
    distanceFromSun: '778.5 million km',
    temperature: '-110°C average',
    atmosphere: 'Hydrogen and helium with storm bands',
    gravity: '2.53 g',
    color: '#d7a56f',
    textureUrl: '/textures/jupiter.png',
    surfaceTag: 'Banded gas giant',
    moonCount: 95,
    magneticField: 'Very strong magnetosphere',
    explorationDifficulty: 'High',
    discoveryStatus: 'Ancient observation',
    orbitalPeriod: '11.9 Earth years',
    rotationPeriod: '9.9 hours',
    moons: [
      { name: 'Io', orbitRadius: 2.0, size: 0.08, color: '#facc15', period: '1.8 days' },
      { name: 'Europa', orbitRadius: 2.45, size: 0.07, color: '#e5e7eb', period: '3.5 days' },
      { name: 'Ganymede', orbitRadius: 2.9, size: 0.1, color: '#a8a29e', period: '7.2 days' },
      { name: 'Callisto', orbitRadius: 3.35, size: 0.09, color: '#78716c', period: '16.7 days' },
    ],
    missionHighlights: ['Pioneer and Voyager flybys', 'Galileo orbiter', 'Juno polar mission'],
    visualPalette: ['#7c2d12', '#b45309', '#d7a56f', '#fef3c7'],
    namingOrigin: 'Jupiter was named after the king of the Roman gods.',
    archiveNote: 'Jupiter anchors the outer planets with immense gravity, turbulent belts, and a long-lived storm system.',
    observationRecord: {
      firstKnown: 'Ancient times',
      telescopicObservation: 'Galileo observed its four largest moons in 1610',
      spaceMissions: 'Pioneer, Voyager, Galileo, Juno',
    },
    callouts: [
      { label: 'Great Red Spot', description: 'A persistent storm larger than Earth', position: 'top-right' },
      { label: 'Cloud belts', description: 'Fast winds form alternating bands', position: 'right' },
      { label: 'Galilean moons', description: 'Four large moons form a miniature system', position: 'bottom-left' },
    ],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    subtitle: 'The Ringed Giant',
    category: 'GIANT PLANETS',
    type: 'Gas Giant',
    diameter: '116,460 km',
    distanceFromSun: '1.43 billion km',
    temperature: '-178°C average',
    atmosphere: 'Hydrogen and helium',
    gravity: '1.07 g',
    color: '#d6b16a',
    textureUrl: '/textures/saturn.png',
    surfaceTag: 'Ringed gas giant',
    moonCount: 146,
    magneticField: 'Strong global field',
    explorationDifficulty: 'High',
    discoveryStatus: 'Ancient observation',
    orbitalPeriod: '29.5 Earth years',
    rotationPeriod: '10.7 hours',
    moons: [
      { name: 'Titan', orbitRadius: 2.45, size: 0.11, color: '#d97706', period: '15.9 days' },
      { name: 'Enceladus', orbitRadius: 3.0, size: 0.06, color: '#e0f2fe', period: '1.4 days' },
      { name: 'Rhea', orbitRadius: 3.45, size: 0.07, color: '#cbd5e1', period: '4.5 days' },
    ],
    missionHighlights: ['Pioneer 11 flyby', 'Voyager encounters', 'Cassini-Huygens mission'],
    visualPalette: ['#78350f', '#b45309', '#d6b16a', '#fde68a'],
    namingOrigin: 'Saturn was named after the Roman god of agriculture and time.',
    archiveNote: "Saturn's rings turn scientific observation into one of the most iconic visual symbols in astronomy.",
    observationRecord: {
      firstKnown: 'Ancient times',
      telescopicObservation: 'Galileo observed its unusual shape in 1610',
      spaceMissions: 'Pioneer, Voyager, Cassini',
    },
    callouts: [
      { label: 'Ring system', description: 'Ice and dust organized into bright bands', position: 'top-left' },
      { label: 'Titan', description: 'A large moon with lakes and dense air', position: 'right' },
      { label: 'Cassini archive', description: 'Thirteen years of orbital observations', position: 'bottom-right' },
    ],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    subtitle: 'The Sideways Ice Giant',
    category: 'GIANT PLANETS',
    type: 'Ice Giant',
    diameter: '50,724 km',
    distanceFromSun: '2.87 billion km',
    temperature: '-224°C average',
    atmosphere: 'Hydrogen, helium, and methane',
    gravity: '0.89 g',
    color: '#67e8f9',
    textureUrl: '/textures/uranus.png',
    surfaceTag: 'Methane-blue ice giant',
    moonCount: 28,
    magneticField: 'Tilted and offset field',
    explorationDifficulty: 'Very high',
    discoveryStatus: 'Discovered by telescope',
    orbitalPeriod: '84 Earth years',
    rotationPeriod: '17.2 hours retrograde',
    moons: [
      { name: 'Titania', orbitRadius: 2.3, size: 0.07, color: '#cbd5e1', period: '8.7 days' },
      { name: 'Oberon', orbitRadius: 2.9, size: 0.07, color: '#94a3b8', period: '13.5 days' },
      { name: 'Miranda', orbitRadius: 3.35, size: 0.05, color: '#e2e8f0', period: '1.4 days' },
    ],
    missionHighlights: ['Voyager 2 flyby', 'Hubble monitoring', 'Webb infrared observations'],
    visualPalette: ['#0e7490', '#22d3ee', '#67e8f9', '#cffafe'],
    namingOrigin: 'Uranus was named after the Greek personification of the sky.',
    archiveNote: 'Uranus rolls around the Sun on its side, making its seasons among the strangest in the Solar System.',
    observationRecord: {
      firstKnown: 'Observed before recognition as a planet',
      telescopicObservation: 'William Herschel identified it in 1781',
      spaceMissions: 'Voyager 2 flyby',
    },
    callouts: [
      { label: 'Axial tilt', description: 'The planet rotates almost on its side', position: 'top-right' },
      { label: 'Faint rings', description: 'A subtle dark ring system surrounds it', position: 'left' },
      { label: 'Methane color', description: 'Methane absorbs red light and leaves blue-green tones', position: 'bottom-right' },
    ],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    subtitle: 'The Wind World',
    category: 'GIANT PLANETS',
    type: 'Ice Giant',
    diameter: '49,244 km',
    distanceFromSun: '4.50 billion km',
    temperature: '-214°C average',
    atmosphere: 'Hydrogen, helium, methane',
    gravity: '1.14 g',
    color: '#2563eb',
    textureUrl: '/textures/neptune.png',
    surfaceTag: 'Deep blue ice giant',
    moonCount: 16,
    magneticField: 'Tilted global field',
    explorationDifficulty: 'Very high',
    discoveryStatus: 'Predicted by mathematics',
    orbitalPeriod: '164.8 Earth years',
    rotationPeriod: '16.1 hours',
    moons: [
      { name: 'Triton', orbitRadius: 2.55, size: 0.1, color: '#c4b5fd', period: '5.9 days' },
      { name: 'Nereid', orbitRadius: 3.2, size: 0.04, color: '#94a3b8', period: '360 days' },
    ],
    missionHighlights: ['Voyager 2 flyby', 'Hubble storm tracking', 'Webb atmospheric imaging'],
    visualPalette: ['#172554', '#1d4ed8', '#2563eb', '#93c5fd'],
    namingOrigin: 'Neptune was named after the Roman god of the sea.',
    archiveNote: 'Neptune is an archive of distant winds, dark storms, and a planet found first through calculation.',
    observationRecord: {
      firstKnown: 'Mathematically predicted',
      telescopicObservation: 'Observed in 1846',
      spaceMissions: 'Voyager 2 flyby',
    },
    callouts: [
      { label: 'High winds', description: 'Some of the fastest winds in the Solar System', position: 'right' },
      { label: 'Triton', description: 'A captured moon with a retrograde orbit', position: 'bottom-left' },
      { label: 'Predicted planet', description: 'Its position was inferred before discovery', position: 'top-left' },
    ],
  },
  {
    id: 'pluto',
    name: 'Pluto',
    subtitle: 'The Hearted Dwarf',
    category: 'DWARF / SMALL BODIES',
    type: 'Dwarf Planet',
    diameter: '2,377 km',
    distanceFromSun: '5.91 billion km average',
    temperature: '-229°C average',
    atmosphere: 'Thin nitrogen atmosphere',
    gravity: '0.063 g',
    color: '#c8a27a',
    textureUrl: '/textures/pluto.png',
    surfaceTag: 'Icy Kuiper Belt world',
    moonCount: 5,
    magneticField: 'No known global field',
    explorationDifficulty: 'Extreme',
    discoveryStatus: 'Discovered by telescope',
    orbitalPeriod: '248 Earth years',
    rotationPeriod: '6.4 Earth days',
    moons: [
      { name: 'Charon', orbitRadius: 2.25, size: 0.16, color: '#9ca3af', period: '6.4 days' },
      { name: 'Nix', orbitRadius: 3.0, size: 0.04, color: '#cbd5e1', period: '24.9 days' },
    ],
    missionHighlights: ['New Horizons flyby', 'Charon system imaging', 'Kuiper Belt context'],
    visualPalette: ['#451a03', '#92400e', '#c8a27a', '#fed7aa'],
    namingOrigin: 'Pluto was named after the Roman god of the underworld.',
    archiveNote: 'Pluto reframed the archive itself, forcing a public conversation about classification and planetary identity.',
    observationRecord: {
      firstKnown: 'Discovered in 1930',
      telescopicObservation: 'Clyde Tombaugh discovery plates',
      spaceMissions: 'New Horizons',
    },
    callouts: [
      { label: 'Sputnik Planitia', description: 'A bright nitrogen-ice basin', position: 'top-left' },
      { label: 'Charon pair', description: 'Pluto and Charon orbit a shared center', position: 'right' },
      { label: 'Reclassification', description: 'A landmark case in planetary taxonomy', position: 'bottom-right' },
    ],
  },
  {
    id: 'ceres',
    name: 'Ceres',
    subtitle: 'The Asteroid Belt Dwarf',
    category: 'DWARF / SMALL BODIES',
    type: 'Dwarf Planet',
    diameter: '940 km',
    distanceFromSun: '413.7 million km',
    temperature: '-105°C average',
    atmosphere: 'Trace water vapor exosphere',
    gravity: '0.03 g',
    color: '#8b8178',
    textureUrl: '/textures/ceres.png',
    surfaceTag: 'Salt-bright dwarf world',
    moonCount: 0,
    magneticField: 'No known global field',
    explorationDifficulty: 'Medium',
    discoveryStatus: 'Discovered by telescope',
    orbitalPeriod: '4.6 Earth years',
    rotationPeriod: '9.1 hours',
    moons: [],
    missionHighlights: ['Dawn orbital mapping', 'Occator crater imaging', 'Bright salt deposits'],
    visualPalette: ['#292524', '#57534e', '#8b8178', '#e7e5e4'],
    namingOrigin: 'Ceres was named after the Roman goddess of agriculture.',
    archiveNote: 'Ceres bridges asteroid and planet categories, holding ice, salts, and a story of early Solar System material.',
    observationRecord: {
      firstKnown: 'Discovered in 1801',
      telescopicObservation: 'Giuseppe Piazzi discovery',
      spaceMissions: 'Dawn',
    },
    callouts: [
      { label: 'Occator crater', description: 'Bright salt-rich deposits mark the floor', position: 'top-right' },
      { label: 'Asteroid belt', description: 'Largest object in the main belt', position: 'left' },
      { label: 'Water history', description: 'Evidence suggests brines and ice-rich material', position: 'bottom-right' },
    ],
  },
  {
    id: 'eris',
    name: 'Eris',
    subtitle: 'The Distant Disruptor',
    category: 'DWARF / SMALL BODIES',
    type: 'Dwarf Planet',
    diameter: '2,326 km',
    distanceFromSun: '10.1 billion km average',
    temperature: '-243°C average',
    atmosphere: 'Collapsed volatile frost suspected',
    gravity: '0.084 g',
    color: '#dbeafe',
    textureUrl: '/textures/eris.png',
    surfaceTag: 'Reflective icy dwarf',
    moonCount: 1,
    magneticField: 'Unknown',
    explorationDifficulty: 'Extreme',
    discoveryStatus: 'Discovered by survey imaging',
    orbitalPeriod: '558 Earth years',
    rotationPeriod: '25.9 hours',
    moons: [
      { name: 'Dysnomia', orbitRadius: 2.6, size: 0.06, color: '#cbd5e1', period: '15.8 days' },
    ],
    missionHighlights: ['Palomar survey discovery', 'Dysnomia observations', 'Dwarf planet classification'],
    visualPalette: ['#1e293b', '#64748b', '#dbeafe', '#f8fafc'],
    namingOrigin: 'Eris was named after the Greek goddess of discord.',
    archiveNote: 'Eris helped trigger the debate that redefined Pluto and formalized the dwarf planet category.',
    observationRecord: {
      firstKnown: 'Discovered in 2005',
      telescopicObservation: 'Survey imaging and follow-up observations',
      spaceMissions: 'None',
    },
    callouts: [
      { label: 'High albedo', description: 'A bright icy surface reflects sunlight', position: 'top-left' },
      { label: 'Dysnomia', description: 'A small moon used to estimate mass', position: 'right' },
      { label: 'Taxonomy shift', description: 'Central to modern dwarf planet classification', position: 'bottom-left' },
    ],
  },
  {
    id: 'europa',
    name: 'Europa',
    subtitle: "Jupiter's Ice Ocean Moon",
    category: 'MAJOR MOONS',
    type: 'Natural Satellite',
    diameter: '3,122 km',
    distanceFromSun: 'Orbits Jupiter',
    temperature: '-160°C average',
    atmosphere: 'Thin oxygen exosphere',
    gravity: '0.13 g',
    color: '#e7dcc8',
    textureUrl: '/textures/europa.png',
    surfaceTag: 'Ice shell ocean moon',
    moonCount: 0,
    magneticField: 'Induced field signature',
    explorationDifficulty: 'High',
    discoveryStatus: 'Galilean moon',
    orbitalPeriod: '3.5 Earth days',
    rotationPeriod: '3.5 Earth days',
    moons: [],
    missionHighlights: ['Galileo flybys', 'Europa Clipper mission', 'JUICE flybys planned'],
    visualPalette: ['#78350f', '#b45309', '#e7dcc8', '#f8fafc'],
    namingOrigin: 'Europa was named after a figure from Greek mythology associated with Zeus.',
    archiveNote: 'Europa is one of the strongest archive candidates for a hidden ocean beneath an icy shell.',
    observationRecord: {
      firstKnown: 'Discovered in 1610',
      telescopicObservation: 'Galileo Galilei',
      spaceMissions: 'Voyager, Galileo, Europa Clipper',
    },
    callouts: [
      { label: 'Ice fractures', description: 'Dark lineae cross the bright surface', position: 'top-right' },
      { label: 'Subsurface ocean', description: 'Magnetic evidence suggests salty water below', position: 'right' },
      { label: 'Clipper target', description: 'A major modern exploration priority', position: 'bottom-left' },
    ],
  },
  {
    id: 'titan',
    name: 'Titan',
    subtitle: "Saturn's Hazy Moon",
    category: 'MAJOR MOONS',
    type: 'Natural Satellite',
    diameter: '5,150 km',
    distanceFromSun: 'Orbits Saturn',
    temperature: '-179°C average',
    atmosphere: 'Dense nitrogen with methane haze',
    gravity: '0.14 g',
    color: '#d97706',
    textureUrl: '/textures/titan.png',
    surfaceTag: 'Methane lake world',
    moonCount: 0,
    magneticField: 'No intrinsic global field',
    explorationDifficulty: 'High',
    discoveryStatus: 'Discovered by telescope',
    orbitalPeriod: '15.9 Earth days',
    rotationPeriod: '15.9 Earth days',
    moons: [],
    missionHighlights: ['Cassini radar mapping', 'Huygens landing', 'Dragonfly mission planned'],
    visualPalette: ['#431407', '#92400e', '#d97706', '#fde68a'],
    namingOrigin: 'Titan was named after the Titans of Greek mythology.',
    archiveNote: 'Titan is a world of weather, dunes, lakes, and chemistry under a golden atmosphere.',
    observationRecord: {
      firstKnown: 'Discovered in 1655',
      telescopicObservation: 'Christiaan Huygens',
      spaceMissions: 'Cassini-Huygens, Dragonfly planned',
    },
    callouts: [
      { label: 'Methane lakes', description: 'Liquid hydrocarbons collect near the poles', position: 'top-left' },
      { label: 'Thick haze', description: 'A dense atmosphere hides the surface', position: 'right' },
      { label: 'Dragonfly', description: 'Rotorcraft mission planned for surface exploration', position: 'bottom-right' },
    ],
  },
  {
    id: 'ganymede',
    name: 'Ganymede',
    subtitle: 'The Largest Moon',
    category: 'MAJOR MOONS',
    type: 'Natural Satellite',
    diameter: '5,268 km',
    distanceFromSun: 'Orbits Jupiter',
    temperature: '-163°C average',
    atmosphere: 'Thin oxygen exosphere',
    gravity: '0.15 g',
    color: '#a8a29e',
    textureUrl: '/textures/ganymede.png',
    surfaceTag: 'Magnetic icy moon',
    moonCount: 0,
    magneticField: 'Intrinsic magnetic field',
    explorationDifficulty: 'High',
    discoveryStatus: 'Galilean moon',
    orbitalPeriod: '7.2 Earth days',
    rotationPeriod: '7.2 Earth days',
    moons: [],
    missionHighlights: ['Voyager imaging', 'Galileo orbital passes', 'JUICE primary target'],
    visualPalette: ['#292524', '#78716c', '#a8a29e', '#e7e5e4'],
    namingOrigin: 'Ganymede was named after a divine cupbearer from Greek mythology.',
    archiveNote: 'Ganymede is larger than Mercury and remains the only moon known with its own magnetic field.',
    observationRecord: {
      firstKnown: 'Discovered in 1610',
      telescopicObservation: 'Galileo Galilei',
      spaceMissions: 'Voyager, Galileo, JUICE planned',
    },
    callouts: [
      { label: 'Largest moon', description: 'Bigger than Mercury, though less massive', position: 'top-right' },
      { label: 'Magnetic field', description: 'Unique among known moons', position: 'right' },
      { label: 'Grooved terrain', description: 'Ancient tectonic-like surface patterns', position: 'bottom-left' },
    ],
  },
  {
    id: 'enceladus',
    name: 'Enceladus',
    subtitle: "Saturn's Plume Moon",
    category: 'MAJOR MOONS',
    type: 'Natural Satellite',
    diameter: '504 km',
    distanceFromSun: 'Orbits Saturn',
    temperature: '-201°C average',
    atmosphere: 'Water vapor plume environment',
    gravity: '0.011 g',
    color: '#e0f2fe',
    textureUrl: '/textures/enceladus.png',
    surfaceTag: 'Cryovolcanic ice moon',
    moonCount: 0,
    magneticField: 'No intrinsic field',
    explorationDifficulty: 'High',
    discoveryStatus: 'Discovered by telescope',
    orbitalPeriod: '1.4 Earth days',
    rotationPeriod: '1.4 Earth days',
    moons: [],
    missionHighlights: ['Cassini plume flythroughs', 'Tiger stripe imaging', 'Ocean chemistry sampling'],
    visualPalette: ['#0f172a', '#38bdf8', '#e0f2fe', '#ffffff'],
    namingOrigin: 'Enceladus was named after a giant from Greek mythology.',
    archiveNote: 'Enceladus changed how archives describe habitability: a small icy moon can vent ocean material into space.',
    observationRecord: {
      firstKnown: 'Discovered in 1789',
      telescopicObservation: 'William Herschel',
      spaceMissions: 'Voyager, Cassini',
    },
    callouts: [
      { label: 'South pole plumes', description: 'Jets of water vapor and ice grains', position: 'top-left' },
      { label: 'Tiger stripes', description: 'Warm fractures feed the geysers', position: 'right' },
      { label: 'Ocean access', description: 'Plumes expose material from below the ice', position: 'bottom-right' },
    ],
  },
  {
    id: 'kepler-186f',
    name: 'Kepler-186f',
    subtitle: 'First Earth-Sized Habitable-Zone Find',
    category: 'EXOPLANET ARCHIVE',
    type: 'Exoplanet',
    diameter: 'About 1.1 Earth radii',
    distanceFromSun: 'About 580 light-years',
    temperature: 'Unknown equilibrium range',
    atmosphere: 'Unknown',
    gravity: 'Estimated near Earth-like',
    color: '#22c55e',
    textureUrl: '/textures/kepler-186f.png',
    surfaceTag: 'Habitable-zone candidate',
    moonCount: 0,
    magneticField: 'Unknown',
    explorationDifficulty: 'Remote observation only',
    discoveryStatus: 'Transit discovery',
    orbitalPeriod: '129.9 Earth days',
    rotationPeriod: 'Unknown',
    moons: [],
    missionHighlights: ['Kepler transit detection', 'Habitable-zone classification', 'Radius constraint archive'],
    visualPalette: ['#052e16', '#15803d', '#22c55e', '#bbf7d0'],
    namingOrigin: 'Kepler-186f is named for the Kepler mission catalog and its host star system.',
    archiveNote: 'Kepler-186f widened the archive of potentially temperate rocky worlds beyond the Solar System.',
    observationRecord: {
      firstKnown: 'Announced in 2014',
      telescopicObservation: 'Kepler space telescope transit data',
      spaceMissions: 'Kepler',
    },
    callouts: [
      { label: 'Habitable zone', description: 'Receives stellar energy in a temperate range', position: 'top-right' },
      { label: 'Transit method', description: 'Detected as a tiny dip in starlight', position: 'right' },
      { label: 'Remote world', description: 'Physical details remain model-dependent', position: 'bottom-left' },
    ],
  },
  {
    id: 'trappist-1e',
    name: 'TRAPPIST-1e',
    subtitle: 'Compact System Candidate',
    category: 'EXOPLANET ARCHIVE',
    type: 'Exoplanet',
    diameter: 'About 0.92 Earth radii',
    distanceFromSun: 'About 40.7 light-years',
    temperature: 'Temperate equilibrium range',
    atmosphere: 'Unknown; under study',
    gravity: 'About 0.93 g',
    color: '#ef4444',
    textureUrl: '/textures/trappist-1e.png',
    surfaceTag: 'Temperate rocky exoplanet',
    moonCount: 0,
    magneticField: 'Unknown',
    explorationDifficulty: 'Remote observation only',
    discoveryStatus: 'Transit discovery',
    orbitalPeriod: '6.1 Earth days',
    rotationPeriod: 'Likely tidally locked',
    moons: [],
    missionHighlights: ['TRAPPIST discovery campaign', 'Spitzer transit refinement', 'JWST atmosphere studies'],
    visualPalette: ['#450a0a', '#991b1b', '#ef4444', '#fecaca'],
    namingOrigin: 'TRAPPIST-1e is named for the TRAPPIST telescope survey and its host star system.',
    archiveNote: 'TRAPPIST-1e represents the new archive problem: many promising worlds, little direct surface certainty.',
    observationRecord: {
      firstKnown: 'Announced in 2017',
      telescopicObservation: 'TRAPPIST and Spitzer transit observations',
      spaceMissions: 'Spitzer, JWST observations',
    },
    callouts: [
      { label: 'Compact orbit', description: 'A short year around a cool dwarf star', position: 'top-left' },
      { label: 'Atmosphere search', description: 'Transit spectra test for gases', position: 'right' },
      { label: 'Habitability study', description: 'A key comparative exoplanet target', position: 'bottom-right' },
    ],
  },
  {
    id: 'proxima-centauri-b',
    name: 'Proxima Centauri b',
    subtitle: 'Nearest Exoplanet Candidate',
    category: 'EXOPLANET ARCHIVE',
    type: 'Exoplanet',
    diameter: 'Minimum mass about 1.1 Earths',
    distanceFromSun: '4.24 light-years',
    temperature: 'Unknown; irradiation may be temperate',
    atmosphere: 'Unknown',
    gravity: 'Unknown',
    color: '#a855f7',
    textureUrl: '/textures/proxima-centauri-b.png',
    surfaceTag: 'Nearest temperate candidate',
    moonCount: 0,
    magneticField: 'Unknown',
    explorationDifficulty: 'Extreme remote observation',
    discoveryStatus: 'Radial velocity discovery',
    orbitalPeriod: '11.2 Earth days',
    rotationPeriod: 'Unknown; likely influenced by tides',
    moons: [],
    missionHighlights: ['Radial velocity detection', 'Nearest-star archive target', 'Ongoing confirmation studies'],
    visualPalette: ['#2e1065', '#7e22ce', '#a855f7', '#ddd6fe'],
    namingOrigin: 'The planet is named for its host star, Proxima Centauri, the nearest star to the Sun.',
    archiveNote: 'Proxima Centauri b sits at the edge of imagination and measurement: close in light-years, distant in certainty.',
    observationRecord: {
      firstKnown: 'Announced in 2016',
      telescopicObservation: 'Radial velocity measurements',
      spaceMissions: 'Ground-based and space telescope follow-up',
    },
    callouts: [
      { label: 'Nearest candidate', description: 'The closest known exoplanet archive target', position: 'top-right' },
      { label: 'Radial velocity', description: 'Detected by its tug on the host star', position: 'left' },
      { label: 'Red dwarf environment', description: 'Stellar activity shapes habitability questions', position: 'bottom-right' },
    ],
  },
]

export function getPlanet(planetId) {
  return PLANETS.find((planet) => planet.id === planetId) ?? PLANETS[0]
}
